openapi: 3.0.1
info:
  title: zonebycr
  description: API Definition of zonebycr
  version: 1.0.0
servers:
- url: http://localhost:8290/Sysapi
paths:
  /:
    get:
      responses:
        default:
          description: Default response
